In [2]:
from sklearn.dummy import DummyClassifier
from sklearn import datasets
import numpy as np
import sklearn

In [3]:
model = DummyClassifier(strategy="most_frequent")

In [4]:
X, y = datasets.make_circles()
y = y.reshape(-1,1)

In [5]:
X.shape, y.shape

((100, 2), (100, 1))

In [6]:
model.fit(X,y)

DummyClassifier(strategy='most_frequent')

## Playing around

In [39]:
mask = np.where(y==0)[0]
refined = X[mask]
print(refined.shape)

(50, 2)


In [42]:
import pandas as pd

In [71]:
df = pd.DataFrame(X)
y_df = pd.DataFrame(y)
df.shape

(100, 2)

In [46]:
df.head()

0         1
0 -0.583175  0.547638
1 -0.050232  0.798421
2  0.187381 -0.982287
3  0.309017  0.951057
4 -0.247214  0.760845

In [52]:
df[y==0].shape
# need to convert the other to dataframe as well

(50, 2)

In [69]:
pre = "col_processed_"
for i,col_i in df.T.iterrows():
    for j, col_j in df.T.iterrows():
        df[pre+str(i)] = col_i * col_j

In [70]:
df

0         1  col_processed_0  col_processed_1
0  -0.583175  0.547638        -0.319369        -0.174898
1  -0.050232  0.798421        -0.040107        -0.032022
2   0.187381 -0.982287        -0.184062         0.180802
3   0.309017  0.951057         0.293893         0.279508
4  -0.247214  0.760845        -0.188091        -0.143108
..       ...       ...              ...              ...
95  0.149905 -0.785830        -0.117800         0.092571
96 -0.247214 -0.760845         0.188091        -0.143108
97  0.992115  0.125333         0.124345         0.015585
98 -0.062791 -0.998027         0.062667        -0.062543
99 -0.583175 -0.547638         0.319369        -0.174898

[100 rows x 4 columns]

In [104]:
#NUMPY
XB = X.copy()

In [96]:
X.shape[1]

2

In [105]:
M, N = X.shape
for i in range(N):
    for j in range(N):
        if(i == j):
            continue
        print(i, j)
        #print("DIM ", XB, "  ", X[:,i].shape, "  ", X[:,j].shape)
        XB = np.hstack([XB, X[:,i].reshape(-1,1) *  X[:,j].reshape(-1,1)])

0 1
1 0


In [106]:
XB.shape

(100, 4)

In [107]:
XB

array([[-5.83174902e-01,  5.47637685e-01, -3.19368553e-01,
        -3.19368553e-01],
       [-5.02324156e-02,  7.98421383e-01, -4.01066347e-02,
        -4.01066347e-02],
       [ 1.87381315e-01, -9.82287251e-01, -1.84062276e-01,
        -1.84062276e-01],
       [ 3.09016994e-01,  9.51056516e-01,  2.93892626e-01,
         2.93892626e-01],
       [-2.47213595e-01,  7.60845213e-01, -1.88091281e-01,
        -1.88091281e-01],
       [-7.93691761e-01, -1.00266587e-01,  7.95807639e-02,
         7.95807639e-02],
       [-5.35826795e-01, -8.44327926e-01,  4.52413526e-01,
         4.52413526e-01],
       [ 9.92114701e-01, -1.25333234e-01, -1.24344944e-01,
        -1.24344944e-01],
       [ 8.76306680e-01,  4.81753674e-01,  4.22163963e-01,
         4.22163963e-01],
       [ 5.02324156e-02,  7.98421383e-01,  4.01066347e-02,
         4.01066347e-02],
       [-5.02324156e-02, -7.98421383e-01,  4.01066347e-02,
         4.01066347e-02],
       [-7.43821189e-01, -2.94499642e-01,  2.19055074e-01,
      

In [108]:
XBDF = pd.DataFrame(XB)
XBDF.shape

(100, 4)

In [109]:
XBDF

0         1         2         3
0  -0.583175  0.547638 -0.319369 -0.319369
1  -0.050232  0.798421 -0.040107 -0.040107
2   0.187381 -0.982287 -0.184062 -0.184062
3   0.309017  0.951057  0.293893  0.293893
4  -0.247214  0.760845 -0.188091 -0.188091
..       ...       ...       ...       ...
95  0.149905 -0.785830 -0.117800 -0.117800
96 -0.247214 -0.760845  0.188091  0.188091
97  0.992115  0.125333  0.124345  0.124345
98 -0.062791 -0.998027  0.062667  0.062667
99 -0.583175 -0.547638  0.319369  0.319369

[100 rows x 4 columns]

## TP/FP/TN/FN, preicison, recall, f1_score


In [72]:
y_hat = model.predict(X)

In [73]:
y_hat

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [74]:
total = y_hat.shape[0]

In [75]:
def confusion_matrix(y, y_hat):
    total = y.shape[0]
    # here 0 is positive, usually 0 is taken as negative
    TP = 0
    FP = 0
    TN = 0
    FN = 0
    
    for i in range(total):
        if(y[i] == 0):
            if(y_hat[i] == 0):
                TP += 1
            else:
                FN += 1
        else:
            if(y_hat[i] == 1):
                TN += 1
            else:
                FP += 1

    
    return TP, FP, TN, FN


In [76]:
TP, FP, TN, FN = confusion_matrix(y, y_hat)

print("TP = ", TP, "TN = ", TN)
print("FP = ", FP, "FN = ", FN)

TP =  50 TN =  0
FP =  50 FN =  0


In [91]:
from sklearn.metrics import confusion_matrix, accuracy_score # .ravel() makes everything a one single long vector
confusion_matrix(y, y_hat)

array([[50,  0],
       [50,  0]])

In [78]:
vec = confusion_matrix(y, y_hat)

In [79]:
vec.ravel()

array([50,  0, 50,  0])

In [92]:
accuracy = (TP+TN)/(TP+TN+FP+FN)
accuracy

0.5

In [93]:
accuracy = accuracy_score(y, y_hat)
accuracy

0.5

In [80]:
precision = (TP)/(TP+FP) 
precision

0.5

In [81]:
recall = (TP) / (TP+FN)
recall

1.0

In [82]:
F1_Score = (2 * precision * recall)/(precision + recall)
F1_Score

0.6666666666666666

In [83]:
from sklearn.metrics import precision_score, recall_score, f1_score

In [84]:
precision_score(y, y_hat, average=None)[0]

/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1334: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


0.5

In [85]:
recall_score(y, y_hat, average=None)[0]

1.0

In [86]:
f1_score(y, y_hat, average=None)[0]

0.6666666666666666

## matthews correlation coefficient

In [88]:
MCC = (TP * TN - FP*FN)/ ((TP+FP) * (TP+FN) * (FN+TP) * (TN+FN) + 0.1)

In [90]:
MCC

0.0